package:
  name: mammal
  version: 1.1.1

source:
  git_url: https://github.com/TheBrownLab/mammal.git

build:
  number: 10

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
  host:
    - r-quadprog
    - r-base
  run:
    - r-quadprog
    - r-base

about:
    home: https://www.mathstat.dal.ca/~tsusko/doc/mammal.pdf
    summary: Accelerated Estimation of Frequency Classes in Site-heterogeneous Profile Mixture Models
